lost-pets/config/routes.rb
Rails.application.routes.draw do
  get '/pets', to: 'pets#index'
  get '/pets/new', to: 'pets#new', as: :new_pet
  get '/pets/:id', to: 'pets#show', as: :pet
  post '/pets', to: 'pets#create'
  get '/pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch '/pets/:id', to: 'pets#update'
  # delete '/pets/:id', to: 'pets#destroy'
end

lost-pets/app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat bird turtle lizard rabbit tiger liger ostrich panda rock)

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

lost-pets/app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :location, :reward, :species, :lost_on, :alive)
  end
end

lost-pets/app/helpers/pets_helper.rb
module PetsHelper
end

lost-pets/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6 offset-md-3 py-5">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

lost-pets/app/views/pets/_form.html.erb
<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :location %>
  <%= f.input :alive, label: 'Wanted alive' %>
  <%= f.input :reward, input_html: { step: 100 } %>
  <%= f.input :lost_on %>
  <%= f.submit pet.persisted? ? 'Update your pet\'s details' : 'List your pet', class: 'btn btn-primary w-100'  %>
<% end %>

lost-pets/app/views/pets/edit.html.erb
<h1>Enter the details of your lost pet</h1>

<%= render 'pets/form', pet: @pet %>

lost-pets/app/views/pets/index.html.erb
<h1 class="mb-5">I lost my pet!!!! Help me!</h1>

<%= link_to "List your lost pet", new_pet_path, class: 'btn btn-outline-primary' %>

<h5>These pets that have been lost!</h5>
<p>Please help the owner find them...</p>

<ul class='list-group'>
  <% @pets.each do |pet| %>
    <li class='list-group-item'><%= link_to pet.name, pet_path(pet) %> (<%= pet.species %>)</li>
  <% end %>
</ul>

lost-pets/app/views/pets/new.html.erb
<h1>Enter the details of your lost pet</h1>

<%= render 'pets/form', pet: @pet %>
  

lost-pets/app/views/pets/show.html.erb
<h1>Details for <%= @pet.name %> (<small><%= @pet.species %></small>)</h1>
<p>Lost <%= time_ago_in_words @pet.lost_on %> ago</p>

<p>Location: <%= @pet.location %></p>
<p>Wanted alive? <%= @pet.alive ? 'YES' : 'NO' %></p>
<p>Reward: ¥<%= @pet.reward %></p>

<%= link_to "Back", pets_path, class: 'btn btn-outline-primary' %>